config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :game_information, only: [:new, :create, :index, :edit, :update]
    resources :teams,            only: [:index, :show, :create, :edit, :update, :destroy]
    resources :players,          only: [:create, :edit, :update, :destroy]
    resources :users,            only: [:index, :show]
    resources :reviews,          only: [:show, :update, :destroy]
    delete 'destroy_evaluation' => 'reviews#destroy_evaluation'
    delete 'reviews/:review_id/comments/:id' => 'reviews#destroy_comment',as: "destroy_comment"
  end


  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    root to: "homes#top"

    resources :users,  only: [:show, :edit, :update] do
      resources :reviews do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only:[:create, :destroy]
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :reviews,      only: [:new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
    get 'reviews_all_team' => 'reviews#reviews_all_team', as: 'reviews_all_team'
    get 'reviews_team' => 'reviews#reviews_team', as: 'reviews_team'


  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/game_information.rb
class GameInformation < ApplicationRecord
  belongs_to :first_team,  class_name: "Team"
  belongs_to :second_team, class_name: "Team"
  has_many :reviews, dependent: :destroy
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :reviews, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :follow, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game_information
  belongs_to :team
  belongs_to :player, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :evaluation, presence: true, on: :create
  validates :point,      presence: true, on: :update

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :game_informations
  has_many :reviews, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :follow
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(follow_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(follow_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @reviews = Review.page(params[:page])
    @user = current_user
  end
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  def create
    @player = Player.new(player_params)
      if @player.save
        flash[:notice] = 'ModelClassName was successfully created.'
        redirect_to admin_team_path(@player.team_id)
      else
        render admin_team_path(@player.team_id)
      end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    #byebug
      if @player.update(player_params)
        flash[:notice] = 'Player was successfully updated.'
        redirect_to admin_team_path(@player.team_id)
      else
        render :edit
      end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to admin_team_path(@player.team_id)
  end

  private

  def player_params
    params.require(:player).permit(:team_id, :name)
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to "/admin/users"
  end

  def destroy_evaluation
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_review_path(review)
  end

  def destroy_comment
    @review = Review.find(params[:review_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_review_path(@review)
  end

end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < ApplicationController
  def index
    @team = Team.new
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @player = Player.new
    @players = @team.players
  end

  def create
    @team = Team.new(team_params)
      if @team.save
        flash[:notice] = 'Team was successfully created.'
        redirect_to admin_teams_path
      else
        render :index
      end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
      if @team.update(team_params)
        flash[:notice] = 'Team was successfully updated.'
        redirect_to "/admin/teams"
      else
        render :edit
      end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to "/admin/teams"
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @reviews = Review.page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin_and_user!, except: [:top]
  #before_action :authenticate_user!, except: [:top]
  private
  def authenticate_admin_and_user!
    if admin_signed_in?
      true
    else
      authenticate_user!
    end
  end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/teams_helper.rb
module Admin::TeamsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/players/edit.html.erb
<h2>選手編集</h2>
<%= form_with model: @player, url: admin_player_path, method: :patch do |f| %>
<table>
    <tbody>
      <tr>
       <td>
        <label for="inputName">球団id</label>
        <%= f.select :team_id, Team.ids %>
       </td>
      </tr>
      <tr>
       <td>
        <label for="inputName">選手名</label>
  　　　　<%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"選手名"%>
       </td>
      </tr>
    </tbody>
  </table>
  <%= f.submit "変更を保存",class:"btn btn-success" %>
<% end %>

app/views/admin/teams/edit.html.erb
<h2>球団編集</h2>
<%= form_with model: @team, url: admin_team_path, method: :patch do |f| %>
<table>
    <tbody>
      <tr>
       <td>
        <label for="inputName">球団名</label>
  　　　　<%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"球団名"%>
       </td>
      </tr>
    </tbody>
  </table>
  <%= f.submit "変更を保存",class:"btn btn-success" %>
<% end %>

app/views/admin/teams/index.html.erb
<h2>球団一覧・追加</h2>
<%= form_with model: @team, url: admin_teams_path, method: :post do |f| %>
<h4>球団名</h4>
<%= f.text_field :name %>
<%= f.submit '新規登録', class:"btn btn-success" %>
<% end %>

<p>ジャンル</p>
<table>
  <thead>
      <th>球団名</th>
      <th></th>
  </thead>
  <tbody>
   <% @teams.each do |team| %>
   <tr>
    <td><%= team.name %></td>
    <td><%= link_to '編集する', edit_admin_team_path(team), class:"btn btn-success" %></td>
    <td><%= link_to '削除する', admin_team_path(team), method: :delete, class:"btn btn-danger" %></td>
    <td><%= link_to '球団詳細', admin_team_path(team.id), class:"btn btn-primary" %></td>
   </tr>
   <% end %>
  </tbody>
</table>

app/views/admin/teams/show.html.erb
<h2><%= @team.name%> 球団詳細</h2>
<%= form_with model: @player, url: admin_players_path, method: :post do |f| %>
<h4>選手名</h4>
<%= f.text_field :name %>
<%= f.hidden_field :team_id, value: @team.id %>
<%= f.submit '新規登録', class:"btn btn-success" %>
<% end %>

<table>
  <thead>
      <th>選手名</th>
      <th></th>
  </thead>
  <tbody>
   <% @players.each do |player| %>
   <tr>
    <td><%= player.name %></td>
    <td><%= link_to '編集する', edit_admin_player_path(player), class:"btn btn-success" %></td>
    <td><%= link_to '削除する', admin_player_path(player), method: :delete, class:"btn btn-danger" %></td>
   <% end %>
  </tbody>
</table>

app/views/admin/users/index.html.erb
<h2>ユーザー一覧</h2>
  <table class="table table-bordered">
    <thead>
      <th>ユーザーID</th>
      <th>ユーザー名</th>
      <th>メールアドレス</th>
    </thead>
    <tbody>
　　　<% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td>
          <%= link_to admin_user_path(user.id) do %>
          <%= user.name %>
          <% end %>
        </td>
        <td><%= user.email %></td>
      </tr>
　　　<% end %>
    </tbody>
  </table>

<%= paginate @users %>

app/views/admin/users/show.html.erb
<h2><%= @user.name %>さんのレビュー一覧</h2>
<table>
  <thead>
      <th>投稿日時</th>
      <th>評価球団</th>
      <th>試合日時</th>
      <th></th>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
    <tr>
      <td><%= review.created_at.strftime('%Y/%m/%d') %></td>
      <td><%= review.team.name %></td>
      <td><%= review.game_information.game_day %></td>
      <td><%= link_to 'レビュー詳細', admin_review_path(review), class:"btn btn-success" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @reviews %>