config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :game_information, only: [:new, :create, :index, :edit, :update]
    resources :teams,            only: [:index, :show, :create, :edit, :update, :destroy]
    resources :players,          only: [:create, :edit, :update, :destroy]
    resources :users,            only: [:index, :show]
    resources :reviews,          only: [:show, :update, :destroy]
    delete 'destroy_evaluation' => 'reviews#destroy_evaluation'
    delete 'reviews/:review_id/comments/:id' => 'reviews#destroy_comment',as: "destroy_comment"
  end


  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    root to: "homes#top"

    resources :users,  only: [:show, :edit, :update] do
      resources :reviews do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only:[:create, :destroy]
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :reviews,      only: [:new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
    get 'reviews_all_team' => 'reviews#reviews_all_team', as: 'reviews_all_team'
    get 'reviews_team' => 'reviews#reviews_team', as: 'reviews_team'


  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/game_information.rb
class GameInformation < ApplicationRecord
  belongs_to :first_team,  class_name: "Team"
  belongs_to :second_team, class_name: "Team"
  has_many :reviews, dependent: :destroy
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :reviews, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :follow, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game_information
  belongs_to :team
  belongs_to :player, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :evaluation, presence: true, on: :create
  validates :point,      presence: true, on: :update

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :game_informations
  has_many :reviews, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :follow
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(follow_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(follow_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admin/game_information_controller.rb
class Admin::GameInformationController < ApplicationController
  def new
    @game_information = GameInformation.new
  end

  def create
    @game_information = GameInformation.new(game_information_params)
      if @game_information.save
        flash[:notice] = 'Game was successfully created.'
        redirect_to admin_game_information_index_path
      else
        render :new
      end
  end

  def index
    game_information_all = GameInformation.all
    @game_informations = {}
    # [Sun, 05 Mar 2023, Sun, 26 Mar 2023]
    GameInformation.pluck(:game_day).uniq.each do |day|
      game_information_all.each do |game_info|
        if game_info.game_day == day
          @game_informations[day] = [] if @game_informations[day].nil?
          @game_informations[day] << game_info
        end
      end
    end
  end

  def edit
    @game_information = GameInformation.find(params[:id])
  end

  def update
    @game_information = GameInformation.find(params[:id])
      if @game_information.update(game_information_params)
        flash[:notice] = 'Game was successfully updated.'
        redirect_to admin_game_information_index_path
      else
        render :edit
      end
  end

  private

  def game_information_params
    params.require(:game_information).permit(:first_team_id, :second_team_id, :game_day, :first_team_point, :second_team_point)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @reviews = Review.page(params[:page])
    @user = current_user
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < ApplicationController
  def index
    @team = Team.new
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @player = Player.new
    @players = @team.players
  end

  def create
    @team = Team.new(team_params)
      if @team.save
        flash[:notice] = 'Team was successfully created.'
        redirect_to admin_teams_path
      else
        render :index
      end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
      if @team.update(team_params)
        flash[:notice] = 'Team was successfully updated.'
        redirect_to "/admin/teams"
      else
        render :edit
      end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to "/admin/teams"
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @reviews = Review.page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin_and_user!, except: [:top]
  #before_action :authenticate_user!, except: [:top]
  private
  def authenticate_admin_and_user!
    if admin_signed_in?
      true
    else
      authenticate_user!
    end
  end
end

app/helpers/admin/game_information_helper.rb
module Admin::GameInformationHelper
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/teams_helper.rb
module Admin::TeamsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/game_information/edit.html.erb
<h1>試合情報編集</h1>
<%= form_with model: @game_information, url: admin_game_information_path, method: :patch do |f| %>
  <table>
     <tbody>
      <tr>
        <td>
          <label for="inputName">試合日</label>
          <%= f.text_field :game_day, autofocus: true, id:"inputName", placeholder:"試合日" %>
        </td>
      </tr>
      <tr>
        <td>
          <label for="inputName">先行球団名</label>
          <%= f.select :first_team_id, options_from_collection_for_select(Team.all, :id, :name) %>
        </td>
      </tr>
      <tr>
        <td>
          <label for="inputName">得点</label>
          <%= f.select :first_team_point, *[1..99], autofocus: true, id:"inputName", placeholder:"得点" %>
        </td>
      </tr>

      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>

      <td>VS</td>

      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>

      <tr>
        <td>
          <label for="inputName">後攻球団名</label>
          <%= f.select :second_team_id, options_from_collection_for_select(Team.all, :id, :name) %>
        </td>
      </tr>
      <tr>
        <td>
          <label for="inputName">得点</label>
          <%= f.select :second_team_point, *[1..99], autofocus: true, id:"inputName", placeholder:"得点" %>
        </td>
      </tr>

      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>

      <tr>
        <td><%= f.submit "変更を保存",class:"btn btn-success" %></td>
      </tr>
     </tbody>
  </table>
<% end %>

app/views/admin/game_information/index.html.erb
<h2>試合一覧</h2>
<p>
  <%= link_to '＋', new_admin_game_information_path, class:"btn btn-light" %>
</p>

<% @game_informations.each do |day, informations| %>
 <table class="mx-auto">
  <thead>
    <tr>
      <th class="h4">試合日：<%= day %></th>
    </tr>
  </thead>
  <tbody>
    <% informations.each do | info | %>
    <tr>
      <td class="h2 p-3">
        <%= info.first_team.name %><%= info.first_team_point %> - <%= info.second_team_point %><%= info.second_team.name %>
      </td>
    </tr>
      <td>
        <div class="text-center">
          <%= link_to '編集する', edit_admin_game_information_path(informations), class:"btn btn-success" %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
 </table>
<% end %>

app/views/admin/game_information/new.html.erb
<h1>新規試合情報登録</h1>
<%= form_with model: @game_information, url: admin_game_information_index_path, method: :post do |f| %>
  <table>
     <tbody>
      <tr>
        <td>試合日</td>
        <td><%= f.text_field :game_day %></td>
      </tr>
      <tr>
        <td>先行球団名</td>
        <td><%= f.select :first_team_id, options_from_collection_for_select(Team.all, :id, :name) %></td>
      </tr>
      <tr>
        <td>先行球団得点</td>
        <td><%= f.select :first_team_point, *[1..99] %></td>
      </tr>

      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>

      <td></td>
      <td>VS</td>

      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>

      <tr>
        <td>後攻球団名</td>
        <td><%= f.select :second_team_id, options_from_collection_for_select(Team.all, :id, :name) %></td>
      </tr>
      <tr>
        <td>後攻球団得点</td>
        <td><%= f.select :second_team_point, *[1..99] %></td>
      </tr>

      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>

      <tr>
        <td><%= f.submit '新規登録' %></td>
      </tr>
     </tbody>
  </table>
<% end %>