config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :game_information, only: [:new, :create, :index, :edit, :update]
    resources :teams,            only: [:index, :show, :create, :edit, :update, :destroy]
    resources :players,          only: [:create, :edit, :update, :destroy]
    resources :users,            only: [:index, :show]
    resources :reviews,          only: [:show, :update, :destroy]
    delete 'destroy_evaluation' => 'reviews#destroy_evaluation'
    delete 'reviews/:review_id/comments/:id' => 'reviews#destroy_comment',as: "destroy_comment"
  end


  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    root to: "homes#top"

    resources :users,  only: [:show, :edit, :update] do
      resources :reviews do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only:[:create, :destroy]
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :reviews,      only: [:new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
    get 'reviews_all_team' => 'reviews#reviews_all_team', as: 'reviews_all_team'
    get 'reviews_team' => 'reviews#reviews_team', as: 'reviews_team'


  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/game_information.rb
class GameInformation < ApplicationRecord
  belongs_to :first_team,  class_name: "Team"
  belongs_to :second_team, class_name: "Team"
  has_many :reviews, dependent: :destroy
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :reviews, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :follow, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game_information
  belongs_to :team
  belongs_to :player, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :evaluation, presence: true, on: :create
  validates :point,      presence: true, on: :update

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :game_informations
  has_many :reviews, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :follow
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(follow_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(follow_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @reviews = Review.page(params[:page])
    @user = current_user
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < ApplicationController
  def index
    @team = Team.new
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @player = Player.new
    @players = @team.players
  end

  def create
    @team = Team.new(team_params)
      if @team.save
        flash[:notice] = 'Team was successfully created.'
        redirect_to admin_teams_path
      else
        render :index
      end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
      if @team.update(team_params)
        flash[:notice] = 'Team was successfully updated.'
        redirect_to "/admin/teams"
      else
        render :edit
      end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to "/admin/teams"
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin_and_user!, except: [:top]
  #before_action :authenticate_user!, except: [:top]
  private
  def authenticate_admin_and_user!
    if admin_signed_in?
      true
    else
      authenticate_user!
    end
  end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/teams_helper.rb
module Admin::TeamsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayerEvaluationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light ">
        <div class="container">
          <a class="navbar-brand", class: 'nav-link text-black' >
            <span>Player Evaluation</span>
          </a>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
           </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
          　　　　ようこそ<%= current_user.name %>さん！
          　　　　<li class="nav-item">
                  <%= link_to "試合一覧", root_path, class: 'nav-link text-black' %>
                </li>
                <li class="nav-item">
                  <%= link_to "マイページ", user_path(current_user), class: 'nav-link text-black' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-black' %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "試合情報一覧", admin_game_information_index_path, class: 'nav-link text-black' %>
                </li>
                <li class="nav-item">
                  <%= link_to "球団一覧", admin_teams_path, class: 'nav-link text-black' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ユーザー一覧", admin_users_path, class: 'nav-link text-black' %>
                </li>
                <li class="nav-item">
                  <%= link_to "全投稿一覧", admin_root_path, class: 'nav-link text-black' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-black' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "試合一覧", root_path, class: 'nav-link text-black' %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-black' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-black' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="container">
     <%= yield %>
    </main>
  </body>
</html>